export type News = {
    id: number,
    title: string,
    sect_president: string,
    sect_HR: string,
    sect_BD: string,
    sect_TD: string,
    sect_Marketing: string,
    weekly_BITizen1: string,
    weekly_BITizen2: string,
    weekly_BITizen3: string,
    BITizen1_img: string,
    BITizen2_img: string,
    BITizen3_img: string,
    BITizen_desc1: string,
    BITizen_desc2: string,
    BITizen_desc3: string,
    date: string,
    thumbnail_img: string
}